version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    domainname: localhost
    hostname: localhost
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    ports:
      - "5121:3306"
    networks:
      - project
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - project
    ports:
        - "5221:9000"
    depends_on:
      - mariadb
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/wp

networks:
  project:
    driver: bridge
